# Generated by Django 5.2.1 on 2025-05-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('step_count', models.IntegerField()),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('calories', models.FloatField()),
                ('active_time', models.IntegerField(help_text='Active time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('calories', models.FloatField()),
                ('speed', models.FloatField(help_text='Speed in m/s')),
                ('device_uuid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Step Count',
                'verbose_name_plural': 'Step Counts',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
